
---
spring:
  config.activate.on-profile: default
  sql.init.platform: h2
cds:
  multitenancy:
    enabled: true
    tenantId: request
  requires:
    db:
      kind: hana
    services:
      SaaSProvisioning:
        service: saas-registry
  data-source.auto-config.enabled: false
  security:
    authentication:
      normalize-provider-tenant: false
    mock:
      enabled: false
    xsuaa:
      enabled: false
    authentication-strategy: never
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
